name: safebill_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.5.1
  go_router: ^14.1.4
  dio: ^5.4.3+1
  google_mlkit_text_recognition: ^0.13.0
  image_picker: ^1.1.1
  flutter_local_notifications: ^18.0.1
  sqflite: ^2.3.3+1
  path_provider: ^2.1.3
  path: ^1.9.0
  intl: ^0.20.2
  timezone: ^0.9.4
  uuid: ^4.5.0
  shared_preferences: ^2.3.2
  google_fonts: ^6.3.3
  google_sign_in: ^6.2.1
  lucide_icons: ^0.257.0
  flutter_animate: ^4.5.2
  connectivity_plus: ^6.0.5
  crypto: ^3.0.5
  file_picker: ^8.1.2
  share_plus: ^10.1.2
  firebase_messaging: ^15.1.3
  firebase_core: ^3.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.9

flutter:
  uses-material-design: true
  assets:
    - img/hero_image.png
